### ISSUE TITLE
Add LinkedIn to connect with others and for a special group associated with Victory for Veterans

### ISSUE THREAD

**Issue by dkibrahi** [donaldmurf/VFV#28]
Create a Linkedin page that will allow users of the game to join the group. Create a character in the game that will instruct users to join a linkedin group.

**Comment by donaldmurf** [comment]
Are you sure you want a branch for this? You don't have to have a branch for an issue that doesn't require any coding. AKA using Unity/C#.

**Comment by dkibrahi** [comment]
Dear Donald,

Yes, I believe the plan was to create a character in the game that would
give the player a way to access the Linkedin page so some code would be
required.

**Comment by donaldmurf** [comment]
I overlooked that on the initial comment. OK. Thanks for clarification. Let me know if you need any help creating a character. @CxBest figured out how to add new static sprites by editing previously used ones. I know how to copy characters, how dialog boxes work, and how to name them. ReplaceKeyWords() in TalkToNPC.cs is where the logic is implemented in the text boxes.

**Comment by CxBest** [comment]
I was able to make the LinkedIn Sprite for you guys and i sent the tiff file for Kareem. I have also attached the png version below. In order to make the png version a tiff file, you can easily just change the extension from png to tiff. if need be, let me know if you need help putting this in the game or i can make a short video how to do this
![LinkedIn_Sprite](https://user-images.githubusercontent.com/103781160/196542037-955b71f9-6617-444c-8211-f3213e663d5e.png)

**Comment by dkibrahi** [comment]
Will add new dialouge
